language: python

python:
  - "3.8"
cache:
  - pip
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
  - pip install pytest
script:
  - pytest
  - sbt clean coverage test
after_success:
  - coveralls
  - sbt coveralls